# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Antonio's Grotto
email: antonio.pastorino@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Un posto dove scrivere di me, dei miei interessi, di quello che faccio e, quando
  capita, di qualcosa di interessante
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://andou.github.io" # the base hostname & protocol for your site
twitter_username: A_Pastorino
github_username:  andou

# Build settings
markdown: kramdown
